-- 1. 扩充原有的 academic_records 表，增加可选大考/小测专属字段
-- 1. 为现有表补上 rank 列 (直接运行此行即可修复 seed 报错)
ALTER TABLE monthly_school_points ADD COLUMN IF NOT EXISTS rank integer;

-- 2. 以下为完整的建表参考 (如果已经建过，运行会跳过)
CREATE TABLE IF NOT EXISTS academic_records (
  id bigint generated by default as identity primary key,
  player_id text not null,
  subject text not null, -- '英语', '数学', '语文', '理综'
  score numeric not null,
  max_score numeric not null default 100,
  is_retest boolean default false,
  event_type text default 'micro_test', -- 'micro_test', 'major_exam'
  event_date date default current_date,
  exam_name text, -- 为新需求补上
  class_avg numeric, -- 为新需求补上
  highest_score numeric, -- 为新需求补上
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS habit_logs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  habit_type text not null, -- '运动', '阅读'
  log_date date default current_date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS monthly_school_points (
  id bigint generated by default as identity primary key,
  player_id text not null,
  month_id text not null, -- 格式: 'YYYY-MM' (例: '2026-03')
  total_score numeric not null,
  rank integer,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 安全地开启 RLS
ALTER TABLE academic_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_school_points ENABLE ROW LEVEL SECURITY;

-- 4. 仅在不存在时创建 Policy
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for academic_records') THEN
        CREATE POLICY "Public Access for academic_records" ON academic_records FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for habit_logs') THEN
        CREATE POLICY "Public Access for habit_logs" ON habit_logs FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for monthly_school_points') THEN
        CREATE POLICY "Public Access for monthly_school_points" ON monthly_school_points FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;
