-- ============================================================
-- GrowSync Database Schema (Supabase / PostgreSQL)
-- Run this in the Supabase SQL Editor to bootstrap or update.
-- All statements are idempotent (safe to re-run).
-- ============================================================

-- 1. Core Tables
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS academic_records (
  id bigint generated by default as identity primary key,
  player_id text not null,
  subject text not null,             -- '英语', '数学', '语文', '理综'
  score numeric not null,
  max_score numeric not null default 100,
  is_retest boolean default false,
  event_type text default 'micro_test', -- 'micro_test', 'major_exam'
  event_date date default current_date,
  exam_name text,
  class_avg numeric,
  highest_score numeric,
  class_rank integer,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS habit_logs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  habit_type text not null,          -- '运动', '阅读'
  log_date date default current_date,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS monthly_school_points (
  id bigint generated by default as identity primary key,
  player_id text not null,
  month_id text not null,            -- 'YYYY-MM' e.g. '2026-03'
  total_score numeric not null,
  rank integer,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS transactions (
  id bigint generated by default as identity primary key,
  player_id text not null,
  amount numeric not null,
  transaction_type text not null,    -- 'earned', 'deducted'
  description text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS quest_proofs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  quest_title text not null,
  quest_type text not null,
  reward_amount numeric not null default 0,
  status text not null default 'pending', -- 'pending', 'under_review', 'approved', 'rejected'
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS habit_proofs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  habit_type text not null,              -- '运动', '阅读'
  log_date date not null,
  proof_type text not null,              -- 'image', 'text'
  proof_url text,                        -- Supabase Storage URL for images
  proof_text text,                       -- Reading summary (>=100 chars)
  status text not null default 'pending', -- 'pending', 'approved', 'rejected'
  reviewed_at timestamptz,
  created_at timestamptz default now() not null
);

-- 2. Incremental column additions (safe if already exists)
-- ------------------------------------------------------------

ALTER TABLE monthly_school_points ADD COLUMN IF NOT EXISTS rank integer;
ALTER TABLE academic_records ADD COLUMN IF NOT EXISTS class_rank integer;
ALTER TABLE academic_records ADD COLUMN IF NOT EXISTS major_exam_rating TEXT CHECK (major_exam_rating IN ('bonus', 'neutral', 'penalty'));
ALTER TABLE academic_records ADD COLUMN IF NOT EXISTS rating_reason TEXT;
ALTER TABLE academic_records ADD COLUMN IF NOT EXISTS is_pass_fail BOOLEAN DEFAULT FALSE;

-- 3. Unique constraints for dedup protection
-- ------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_monthly_player_month'
  ) THEN
    ALTER TABLE monthly_school_points
      ADD CONSTRAINT uq_monthly_player_month UNIQUE (player_id, month_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_habit_player_date_type'
  ) THEN
    ALTER TABLE habit_logs
      ADD CONSTRAINT uq_habit_player_date_type UNIQUE (player_id, log_date, habit_type);
  END IF;
END
$$;

-- 4. Milestone Tasks Table (完本大赏 + 光影计划)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS milestone_tasks (
  id bigint generated by default as identity primary key,
  player_id text not null,

  -- 任务类型与元数据
  task_type text not null,              -- 'book' | 'movie'
  item_name text not null,              -- 书名或影片名
  item_difficulty text,                 -- 难度等级（可选）

  -- 任务配置（由家长设置）
  reward_amount integer not null,       -- 奖励金额（¥）
  deep_questions text[],                -- 深度思考题数组

  -- 用户提交内容
  content_draft text,                   -- 草稿内容（JSON 格式存储各题答案）
  content_submitted text,               -- 正式提交内容
  word_count integer,                   -- 字数统计

  -- 状态管理
  status text not null default 'draft', -- 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected'

  -- 审核相关
  reviewer_notes text,                  -- 审核意见/驳回原因
  reviewed_at timestamptz,

  -- 时间戳
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_milestone_player_status ON milestone_tasks(player_id, status);
CREATE INDEX IF NOT EXISTS idx_milestone_type ON milestone_tasks(task_type);

-- 5. Row Level Security (public access for private project)
-- ------------------------------------------------------------

ALTER TABLE academic_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE milestone_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_school_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quest_proofs ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_proofs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for academic_records') THEN
    CREATE POLICY "Public Access for academic_records" ON academic_records FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for habit_logs') THEN
    CREATE POLICY "Public Access for habit_logs" ON habit_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for monthly_school_points') THEN
    CREATE POLICY "Public Access for monthly_school_points" ON monthly_school_points FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for transactions') THEN
    CREATE POLICY "Public Access for transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for quest_proofs') THEN
    CREATE POLICY "Public Access for quest_proofs" ON quest_proofs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for habit_proofs') THEN
    CREATE POLICY "Public Access for habit_proofs" ON habit_proofs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for milestone_tasks') THEN
    CREATE POLICY "Public Access for milestone_tasks" ON milestone_tasks FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;
