-- ============================================================
-- GrowSync Database Schema (Supabase / PostgreSQL)
-- Run this in the Supabase SQL Editor to bootstrap or update.
-- All statements are idempotent (safe to re-run).
-- ============================================================

-- 1. Core Tables
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS academic_records (
  id bigint generated by default as identity primary key,
  player_id text not null,
  subject text not null,             -- '英语', '数学', '语文', '理综'
  score numeric not null,
  max_score numeric not null default 100,
  is_retest boolean default false,
  event_type text default 'micro_test', -- 'micro_test', 'major_exam'
  event_date date default current_date,
  exam_name text,
  class_avg numeric,
  highest_score numeric,
  class_rank integer,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS habit_logs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  habit_type text not null,          -- '运动', '阅读'
  log_date date default current_date,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS monthly_school_points (
  id bigint generated by default as identity primary key,
  player_id text not null,
  month_id text not null,            -- 'YYYY-MM' e.g. '2026-03'
  total_score numeric not null,
  rank integer,
  notes text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS transactions (
  id bigint generated by default as identity primary key,
  player_id text not null,
  amount numeric not null,
  transaction_type text not null,    -- 'earned', 'deducted'
  description text,
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS quest_proofs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  quest_title text not null,
  quest_type text not null,
  reward_amount numeric not null default 0,
  status text not null default 'pending', -- 'pending', 'under_review', 'approved', 'rejected'
  created_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS habit_proofs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  habit_type text not null,              -- '运动', '阅读'
  log_date date not null,
  proof_type text not null,              -- 'image', 'text'
  proof_url text,                        -- Supabase Storage URL for images
  proof_text text,                       -- Reading summary (>=100 chars)
  status text not null default 'pending', -- 'pending', 'approved', 'rejected'
  reviewed_at timestamptz,
  created_at timestamptz default now() not null
);

-- 2. Incremental column additions (safe if already exists)
-- ------------------------------------------------------------

ALTER TABLE monthly_school_points ADD COLUMN IF NOT EXISTS rank integer;
ALTER TABLE academic_records ADD COLUMN IF NOT EXISTS class_rank integer;

-- 3. Unique constraints for dedup protection
-- ------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_monthly_player_month'
  ) THEN
    ALTER TABLE monthly_school_points
      ADD CONSTRAINT uq_monthly_player_month UNIQUE (player_id, month_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_habit_player_date_type'
  ) THEN
    ALTER TABLE habit_logs
      ADD CONSTRAINT uq_habit_player_date_type UNIQUE (player_id, log_date, habit_type);
  END IF;
END
$$;

-- 4. Row Level Security (public access for private project)
-- ------------------------------------------------------------

ALTER TABLE academic_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_school_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quest_proofs ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_proofs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for academic_records') THEN
    CREATE POLICY "Public Access for academic_records" ON academic_records FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for habit_logs') THEN
    CREATE POLICY "Public Access for habit_logs" ON habit_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for monthly_school_points') THEN
    CREATE POLICY "Public Access for monthly_school_points" ON monthly_school_points FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for transactions') THEN
    CREATE POLICY "Public Access for transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for quest_proofs') THEN
    CREATE POLICY "Public Access for quest_proofs" ON quest_proofs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access for habit_proofs') THEN
    CREATE POLICY "Public Access for habit_proofs" ON habit_proofs FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;
